server {
    listen       80;
    server_name  localhost;

    # 静态资源请求
    location / {
        root   /usr/share/nginx/html;
        index  index.html index.htm;
        # 支持 Vue Router 的 history 模式
        try_files $uri $uri/ /index.html;
    }

    # 动态接口代理 (将 /prod-api/ 转发到后端容器)
    location /prod-api/ {
        proxy_set_header Host $http_host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header REMOTE-HOST $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        
        # 核心魔法：直接通过服务名 ruoyi-backend 访问后端容器！
        proxy_pass http://ruoyi-backend:8080/; 
    }
}